# docker-compose.yml

services:
  # 1) Postgres Database
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  # 2) Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  # 3) Bento Indexer
  indexer:
    build:
      context: .
      dockerfile: indexer.dockerfile
    depends_on:
      - db
    environment:
      RUST_LOG: debug  # Add this line
      RUST_BACKTRACE: 1  # Add this line
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CHAINWEB_NODE_HOST: ${CHAINWEB_NODE_HOST}
      CHAINWEB_NETWORK: ${CHAINWEB_NETWORK}

  # 4) Bento API
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT: ${API_PORT}
    ports:
      - "3000:3000"

  # 5) Metabase (basic ephemeral)
  metabase:
    image: metabase/metabase:latest
    restart: always
    container_name: metabase
    ports:
      - "3001:3000"
    depends_on:
      - db
    # If you don't need persistent Metabase data here, no volumes needed
    # environment: (optional) 
    #   MB_DB_FILE: /metabase.db
